---
- hosts: kubemaster1
  become: true
  tasks:
    - name: Read the content of the file
      slurp:
        path: /home/ajaufura/test.toml
      register: toml_content

    - name: Parse the TOML content
      community.general.toml_query:
        data: "{{ toml_content.content | b64decode }}"
        query: "SystemdCgroup"
      register: toml_result

    - name: Check and update SystemdCgroup key
      block:
        - name: Check if SystemdCgroup is set to true
          set_fact:
            to_update: "{{ toml_result.matches[0].value | default(false) }}"

        - name: Update the value to false if needed
          lineinfile:
            path: /home/ajaufura/test.toml
            regex: '^SystemdCgroup = true$'
            line: 'SystemdCgroup = false'
          when: to_update == true

      rescue:
        - name: Handle the case when SystemdCgroup key is not found
          lineinfile:
            path: /home/ajaufura/test.toml
            line: 'SystemdCgroup = false'
          when: toml_result.matches | length == 0

      when: toml_result.matches | length > 0
