---
- hosts: kubemaster1
  become: true
  tasks:
    - name: Read the content of the file
      slurp:
        path: /home/ajaufura/test.toml
      register: toml_content

    - name: Convert content to string
      set_fact:
        toml_content_string: "{{ toml_content.content | b64decode | decode('utf-8') }}"

    - name: Check if SystemdCgroup key exists and update if needed
      block:
        - name: Find and update SystemdCgroup key to true
          lineinfile:
            path: /home/ajaufura/test.toml
            regex: '^SystemdCgroup\\s*=.*$'
            line: 'SystemdCgroup = true'
          when: "'SystemdCgroup = false' in toml_content_string"

        - name: Add SystemdCgroup key with value true if it doesn't exist
          lineinfile:
            path: /home/ajaufura/test.toml
            line: 'SystemdCgroup = true'
          when: "'SystemdCgroup' not in toml_content_string"

      when: toml_content_string is defined
