---
- hosts: kubemaster1
  become: true
  tasks:
    - name: Ensure SystemdCgroup is set to true in test.toml
      ini_file:
        path: /home/ajaufura/test.toml
        section: 'plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options'
        option: SystemdCgroup
        value: true
