---
- hosts: kubemaster1
  become: true
  tasks:
    - name: Read the content of the file
      slurp:
        path: /home/ajaufura/test.toml
      register: toml_content

    - name: Parse the TOML content and check SystemdCgroup value
      set_fact:
        toml_value: "{{ toml_content.content | b64decode | regex_search('(?m)^SystemdCgroup\\s*=\\s*(\\w+)', '\\1') | default('not_found') }}"

    - name: Update SystemdCgroup key to false if it's set to true
      lineinfile:
        path: /home/ajaufura/test.toml
        regex: '^SystemdCgroup\\s*=\\s*true$'
        line: 'SystemdCgroup = false'
      when: toml_value == 'true'

    - name: Add SystemdCgroup key if it doesn't exist
      lineinfile:
        path: /home/ajaufura/test.toml
        line: 'SystemdCgroup = false'
      when: toml_value == 'not_found'
