---
- hosts: kubemaster1
  become: true
  tasks:
    - name: Ensure SystemdCgroup is set to true in test.toml
      replace:
        path: /home/ajaufura/test.toml
        regexp: '^(\[plugins\."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\].*SystemdCgroup =) (True|False)$'
        replace: '\1 true'
