---
- hosts: kubemaster1
  become: true
  tasks:
  
    - name: Ensure Kubernetes apt repository directory exists
      file:
        path: /etc/apt/sources.list.d
        state: directory
        mode: '0755'

    - name: add Kubernetes apt-key
      apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

    - name: Create kubernetes repo file
      file:
       path: "/etc/apt/sources.list.d/kubernetes.list"
       state: "touch"

    - name: Add K8s Source
      blockinfile:
       path: "/etc/apt/sources.list.d/kubernetes.list"
       block: |
             deb https://apt.kubernetes.io/ kubernetes-xenial main
    
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install kubeadm, kubectl, and kubelet packages
      apt:
        name:
          - kubeadm
          - kubectl
          - kubelet
        state: present
        update_cache: yes

