---
- hosts: kubemaster1
  become: true
  tasks:
  
    - name: Create the /etc/apt/sources.list.d/ directory if it doesn't exist
      file:
        path: /etc/apt/sources.list.d
        state: directory
        mode: '0755'

    - name: Download the Kubernetes apt GPG key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        mode: '0644'

    - name: Add the Kubernetes apt repository to sources list
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
        create: yes

    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install kubeadm, kubectl, and kubelet packages
      apt:
        name:
          - kubeadm
          - kubectl
          - kubelet
        state: present
        update_cache: yes
