---
- name: List Docker Containers
  hosts: all
  gather_facts: false

 tasks:
 - name: Retrive Name of Docker Container
    shell: "docker ps --format '{% raw %}{{ .Names }}{% endraw %}'"
    register: Name
 - name: Retreive Ip of Docker Container
    shell: "docker inspect --format '{%raw %}{{ .NetworkSettings.IPAddress }}{% endraw %}' $(docker ps --format '{% raw %}{{ .Names }}{% endraw %}')"
    register: IP
