---
- name: List Docker Containers
  hosts: all
  gather_facts: false

 tasks:
  - name: Get infos on container
    docker_container_info:
      name: prometheus
    register: result

  - name: Does container exist?
    debug:
      msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

  - name: Print information about container
    debug:
      var: result.container
    when: result.exists

