---
- name: List Docker Containers
  hosts: all
  gather_facts: false

  tasks:
    - name: Get Docker container list
      shell: docker ps --format "{{.Names}}"
      register: docker_output

    - name: Print Docker container names
      debug:
        var: item
      loop: "{{ docker_output.stdout_lines }}"
