---
- hosts: kubemaster1
  become: true
  tasks:
  
    ###### Installing containerd #####
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install containerd package
      apt:
        name: containerd
        state: present
      become: true

    - name: Create the containerd directory
      file:
        path: /etc/containerd
        state: directory

    - name: Run containerd config default and redirect output
      command: containerd config default | sudo tee /etc/containerd/config.toml

    - name: Ensure SystemdCgroup is set to true in config.toml
      ini_file:
        path: /etc/containerd/config.toml
        section: '^\s*plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options\s*$'
        option: '^\s*SystemdCgroup$'
        value: true

    ##### Disable swap #####
    - name: Modify swappiness value
      sysctl:
        name: vm.swappiness
        value: 1
        state: present

    - name: Disable swap
      command: swapoff -a

    - name: Check if swap line is already commented
      command: grep -E '^#.*\sswap\s' /etc/fstab
      register: swap_line_commented
      ignore_errors: yes

    - name: Comment the swap line with backreferences
      lineinfile:
        path: /etc/fstab
        regexp: '^(.*\sswap\s.*)$'
        line: '# \1'
        backrefs: yes
        state: present
      when: swap_line_commented.rc != 0

    - name: Print the modified /etc/fstab
      command: cat /etc/fstab

    - name: Reload /etc/fstab
      command: mount -a

    ##### Enable bridging #####
    - name: Check if ip_forward line is commented in /home/ajaufura/sysctl.conf
      command: grep -E '^#.*net.ipv4.ip_forward.*$' /home/ajaufura/sysctl.conf
      register: ip_forward_line_commented
      changed_when: ip_forward_line_commented.stdout != ""
      ignore_errors: yes

    - name: Uncomment the ip_forward line in /home/ajaufura/sysctl.conf
      lineinfile:
        path: /home/ajaufura/sysctl.conf
        regexp: '^#.*net.ipv4.ip_forward.*$'
        line: 'net.ipv4.ip_forward=1'
        backrefs: no
        state: present
      when: ip_forward_line_commented.stdout != ""

    - name: Print the modified /home/ajaufura/sysctl.conf
      command: cat /home/ajaufura/sysctl.conf

    ##### Enable br_netfilter #####
    - name: Edit k8s.conf file
      blockinfile:
        path: /home/ajaufura/k8s.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - DO NOT MODIFY"
        block: |
          br_netfilter

    - name: Print the modified k8s.conf file
      command: cat /home/ajaufura/k8s.conf
