---
- hosts: kubemaster1
  become: true
  tasks:
    - name: Change the SystemdCgroup value to false
      lineinfile:
        path: /home/ajaufura/test.toml
        line: "SystemdCgroup = false"
        state: present
        create: yes
        insertafter: EOF
        regexp: '^SystemdCgroup\s*='

    - name: Modify swappiness value
      sysctl:
        name: vm.swappiness
        value: 1
        state: present

    - name: Disable swap
      command: swapoff -a

    - name: Check if swap line is already commented
      command: grep -E '^\s*#/.*\sswap\s' /etc/fstab
      register: swap_line_commented
      ignore_errors: yes

    - name: Comment the swap line with backreferences
      lineinfile:
        path: /etc/fstab
        regexp: '^(.*\sswap\s.*)$'
        line: '# \1'
        backrefs: yes
        state: present
      when: swap_line_commented.rc != 0

    - name: Print the modified /etc/fstab
      command: cat /etc/fstab

    - name: Reload /etc/fstab
      command: mount -a
