---
- hosts: kubemaster1
  become: true
  tasks:
    - name: Change the SystemdCgroup value to false
      lineinfile:
        path: /home/ajaufura/test.toml
        line: "SystemdCgroup = false"
        state: present
        create: yes
        insertafter: EOF
        regexp: '^SystemdCgroup\s*='

    - name: Modify swappiness value
      sysctl:
        name: vm.swappiness
        value: 1
        state: present

    - name: Disable swap
      command: swapoff -a

    - name: Check if swap line is already commented
      command: grep -E '^#.*\sswap\s' /etc/fstab
      register: swap_line_commented
      ignore_errors: yes

    - name: Comment the swap line with backreferences
      lineinfile:
        path: /etc/fstab
        regexp: '^(.*\sswap\s.*)$'
        line: '# \1'
        backrefs: yes
        state: present
      when: swap_line_commented.rc != 0

    - name: Print the modified /etc/fstab
      command: cat /etc/fstab

    - name: Reload /etc/fstab
      command: mount -a

    - name: Find the commented line in /home/ajaufura/sysctl.conf
      lineinfile:
        path: /home/ajaufura/sysctl.conf
        regexp: '^#net.ipv4.ip_forward=1'
        state: present
        backup: yes
      register: ip_forward_line

    - name: Uncomment the line if it is commented
      lineinfile:
        path: /home/ajaufura/sysctl.conf
        regexp: '^#net.ipv4.ip_forward=1'
        line: 'net.ipv4.ip_forward=1'
        state: present
      when: ip_forward_line.matched

    - name: Print the modified /home/ajaufura/sysctl.conf
      command: cat /home/ajaufura/sysctl.conf
