---
- name: Update APT cache and upgrade packages
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade APT packages
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
      when: inventory_hostname == play_hosts[0]
