---
- hosts: all
  become: yes
  become_user: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: yes
        force_apt_get: yes
    - name: Reboot if needed
      reboot:
        when: ansible_facts.reboot_required
