---
- name: Update APT cache
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Run apt update
      apt:
        update_cache: yes

- name: Upgrade APT packages
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Run apt upgrade
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
