---
- name: Update and Upgrade APT packages
  hosts: raspeth
  become: yes
  become_method: sudo

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade APT packages
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
      become: yes

