---
- hosts: all  #modify host here
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: full
        force_apt_get: yes
